// GENERATED by tools/registry/gen-registry.ts — DO NOT EDIT
// source: /Users/liam/Documents/Claude/business/synqed/reserve-build-2026-08/testbed-2026-09-14/MANIFEST-DEV-SALON.md
// sha256: 5e1400cba29f42e1a6abc69a7ec3a9a19452405a8907b800979314b4f218c9f3
// fixtures commit: c712c4d56
// generated: 2026-09-22T21:34:54.673Z
export const PRACTICE_REGISTRY = {
  "addendumStores": {
    "La Estro Test Store": "8696b856-11ab-4879-9290-bef40b03ea66"
  },
  "source": {
    "fixturesCommit": "c712c4d56"
  },
  "twins": {
    "appointments": {
      "apt-01": "19337574-cc07-43f7-96b6-60531d04eb1c",
      "apt-02": "fad6d889-6190-4086-93bd-5481f84263ad",
      "apt-03": "6130237f-d992-4446-a23c-b52e9da94b45",
      "apt-04": "8713f6b9-100e-4680-b10e-0ae79d47f401",
      "apt-05": "0e2d1a07-fe38-4912-acf8-09be58d4019e",
      "apt-06": "b2c42b5c-2724-4fa4-a6ae-58c78c11026a",
      "apt-07": "ae5b59ed-3198-4f91-a2a4-f9ce1b9545d6",
      "apt-08": "6e01c6a3-e259-440c-8280-ffdb20d33ea2",
      "apt-09": "0d3e1333-87fb-453a-ab37-5035767fd8c6",
      "apt-10": "6bbccc41-0e0b-44f0-8b1c-79ee22f0d4dc",
      "apt-11": "684123dd-5d7b-46ea-bbb8-ca9704adc83d",
      "apt-12": "03fa1677-872b-4a76-95e9-493d80f20897",
      "apt-13": "2fba5792-eb22-4875-8dc6-c880dfb33288",
      "apt-14": "1bc1c829-e755-49f5-a2e0-ee7e7ee86101",
      "apt-15": "d6b62937-b79d-4518-856e-0989c79674eb",
      "apt-16": "2967fdf4-27ea-46b1-945c-3c3a6a3ffff5",
      "apt-17": "e1e09f24-aba0-46ce-8748-594acac7eb03",
      "apt-18": "507f0af3-d130-42ed-ae42-95d119659eb2",
      "apt-19": "4d7580af-1fb5-404b-98d0-3256dde9a3a4",
      "apt-20": "6f90f6da-b1ab-48e5-859e-2aecccf20689",
      "apt-21": "4bb87659-c366-4881-aa71-701c3f7e46a8",
      "apt-22": "7f23fa2f-13b1-49f5-ad53-17a6ddeca790",
      "apt-23": "3c654cb4-7bd6-41db-b6dc-a7181611f8a4",
      "apt-25": "7ee1cc23-08e0-4686-a48a-f2dad9e97a05",
      "apt-26": "8f0898c4-33d6-47e3-9887-41f5e173b687",
      "apt-27": "74bae3a6-d5f6-4ab6-b07f-ef791e608ada",
      "apt-28": "4eec1b18-dac8-41e1-a0ca-628d8eff98a2",
      "apt-29": "1e24ac5b-3ac3-45d5-9b95-4c32039f51dc",
      "apt-30": "068644e7-368b-4f95-a429-4a02de716578",
      "apt-31": "a533bfa2-b35f-44a8-bbaa-fd3279d6cd65",
      "apt-32": "0f911e53-a3e5-4262-afa9-78ff0b810fc5",
      "apt-33": "04b73e27-1852-42ac-b535-8eed91fb3f4d",
      "apt-34": "6e1fca00-a4e3-4d3a-9ee1-5625b81d1709",
      "apt-35": "b0c3212a-7bed-4830-a8e6-9b7c0002c7ee"
    },
    "customers": {
      "cus-01": "6f771283-c430-48ad-9770-af2ce6848808",
      "cus-02": "a01ed848-969e-4eb5-bfad-98b5530bb45b",
      "cus-03": "c4d42f7a-98d0-44bf-8650-d67b9042497d",
      "cus-04": "219d8e1b-658f-4ec8-960f-8c5db5815d79",
      "cus-05": "f3b15433-b27f-443e-b937-ddc221fc3268",
      "cus-06": "f46235be-82a9-4c2e-82e0-f1a7352e6fd3",
      "cus-07": "554c295d-8599-44b0-8394-790c40cfbfc6",
      "cus-08": "2b9f210f-f802-492d-aa8c-a11cb6c6afa8",
      "cus-09": "cd3dc1e0-dcc6-4554-a5f9-a311863375cc",
      "cus-10": "3f15f192-c01c-4cf2-9cf0-f9d57e3a39d6",
      "cus-11": "5ceaf877-b779-45b9-ad3e-efaffe4cefe3",
      "thin-01": "12953e0a-e638-430f-8d96-7862daac6ec0",
      "thin-02": "65fda38c-0c7b-47ff-8e2e-48d43a48ef0c"
    },
    "menus": {
      "menu-01": "d2884903-7410-4513-b0ef-34586d4522b8",
      "menu-02": "8161483d-0aaa-4465-bac1-710c15f0e2fd",
      "menu-03": "f94116ad-8c1e-4555-bf5f-fb78cd319fea",
      "menu-04": "aaf7a87f-b440-4617-bbb6-d6a0efb1fae3",
      "menu-05": "63a813de-459b-44be-93b4-eae36f24c478",
      "menu-06": "6b0fe7e1-755d-45c3-9a84-4ac49b6f3375"
    },
    "staff": {
      "c-03": "875f0912-9e21-42d0-9f22-673bed198d88",
      "p-01": "088f928a-552b-4068-8ecc-9bc2d9d19cd7",
      "p-02": "17af2de2-c716-425d-9bd4-ea9a6b445aee",
      "p-04": "00a86dcc-1204-4438-b295-e20861f3a137",
      "p-05": "6279b2a0-7f01-4d7b-8644-2f1ce127c947",
      "p-06": "d27c76c4-eda7-4b12-9491-4eb6d9edaee5",
      "p-09": "ff708849-6ed2-4dca-90ae-a7fe2f4ac961"
    },
    "stores": {
      "store-test-daikanyama": "8ac43a4b-7763-4a10-9f73-a662085460af",
      "store-test-ginza": "aa36d5fe-8e35-46bb-8c9b-ac92a8aa816f"
    }
  }
} as const
